add Context and useReducer
kirilliano/react-burger pull request #3
Opened 2023-04-16 00:55 UTC by kirilliano

2023-04-16 05:33 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- В контекст обернуты только те элементы, что будут его использовать
- Реализовали функционал добавления ингредиентов через `useReducer` - так держать!

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- В `App.jsx` вы передаете часть данных через контекст, а часть через пропсы - хотя уже надо всё передавать через контекст.
- Вынесите проверку успешности запроса в отдельную функцию

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-04-16 05:33 UTC, andryxxa93 commented on src/components/app/app.jsx
> +          <ConstructorContext.Provider
**Можно лучше**

такая запись значения контекста приводит к тому, что при каждом рендере App даже не связанным с изменением значения контекста будет создаватсья новый объект и передаваться новое значение контекста, это приведет к перерендеру всех компонентов использующих контекст

Нужно обернуть создание объекта в useMemo, как показано в этой статье https://hswolff.com/blog/how-to-usecontext-with-usereducer/ в разделе Performance Concerns

2023-04-16 05:33 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.jsx
> +        return Promise.reject(`Что-то пошло не так: ${res.status}`);
**Необходимо исправить**
Код функции проверки дублируется два раза, необходимо вынести в отдельную функцию и переиспользовать

2023-04-16 14:26 UTC, kirilliano commented on src/components/app/app.jsx
> +          <ConstructorContext.Provider
Спасибо за статью

2023-04-17 15:06 UTC, andryxxa93 approved these changes
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-04-17 22:17 UTC, merged